Feature - Utopia PHP Storage
utopia-php/storage pull request #1
Opened 2021-01-20 23:51 UTC by lohanidamodar

WIP

2021-01-21 02:12 UTC, lohanidamodar commented
@eldadfux I am having one issue with test, as we are not in docker, the testRoot and testPath are failing, as they return a absolute path. Need help fixing this.
Do we dockerize running tests?

2021-01-21 06:59 UTC, eldadfux commented
Do we need the demo.php file? can we remove it?

Please add a readme, you can use one of the other utopia libs as template. Please include some basic code examples showing different capabilities of cloud functions. Beside that all looks good.

2021-01-21 07:56 UTC, lohanidamodar commented
@eldadfux I believe you mean capabilities of `storage`. Will be working on fixing this

2021-01-21 08:07 UTC, eldadfux commented
hehe yeh sorry, seems like I need a break from cloud functions :)

2021-01-21 08:12 UTC, lohanidamodar commented
@eldadfux I have updated Readme file and removed demo.php, not sure if it's needed. I am sure, it will have something similar already in Readme example.

2021-01-21 08:27 UTC, eldadfux requested changes

2021-01-21 08:27 UTC, eldadfux commented on README.md
> +
Missing init of new Local device. When we have support for S3 please add that as well, and also mention that we support multiple storage adapters in the description

2021-01-21 08:27 UTC, eldadfux commented on README.md
> +## Authors
Can remove this section...

2021-01-22 07:27 UTC, eldadfux approved these changes

2021-01-22 07:27 UTC, merged