feat: add LZ4 compression in storage
utopia-php/storage pull request #55
Opened 2022-10-02 19:10 UTC by aloks98

I have added the LZ4 package for compression, but I cannot get over the fact that the compressed sizes are coming greater than the actual file sizes. Is there something I am missing? Can somebody please help me with this?

2022-10-07 23:57 UTC, stnguyen90 commented
Only local tests:

<img width="1122" alt="image" src="https://user-images.githubusercontent.com/1477010/194676591-66f7b50b-371b-406e-a8e7-11662e8c9fb8.png">

2022-10-08 00:12 UTC, stnguyen90 commented
> I cannot get over the fact that the compressed sizes are coming greater than the actual file sizes

@aloks98, which files are you referring to?

2022-10-08 00:42 UTC, stnguyen90 commented
> I cannot get over the fact that the compressed sizes are coming greater than the actual file sizes. Is there something I am missing? Can somebody please help me with this?

@aloks98, compressing doesn't always yield a smaller file, especially really small files, already compressed files, and files with totally random data. I tested your implementation on the RGB 8 bit version of the artificial image [here](https://imagecompression.info/test_images/) and a file compressed to 13% of the original.

2022-10-08 00:43 UTC, stnguyen90 approved these changes

2022-10-08 00:44 UTC, stnguyen90 commented
@aloks98 Hey 👋 awesome work on your PR! We've approved your work and it'll be merged soon!

2022-10-14 08:34 UTC, christyjacob4 commented on Dockerfile
> +ENV PHP_LZ4_VERSION="master"
Lets not use `master` and stick to using the latest commit hash

2022-10-14 08:35 UTC, christyjacob4 requested changes
Please address the comments

2022-10-15 17:50 UTC, aloks98 commented
hey @christyjacob4
I have updated the version to last commit hash

2022-10-18 23:09 UTC, stnguyen90 requested changes
Sorry, would you please make some additional changes? It seems like the image is failing to build.

2022-10-18 23:09 UTC, stnguyen90 commented on Dockerfile
> +ENV PHP_LZ4_VERSION="8ce521e086fcc4d81c57a60915676673e341ab05"
Let's call this COMMIT instead:

```suggestion
ENV PHP_LZ4_COMMIT="8ce521e086fcc4d81c57a60915676673e341ab05"
```

2022-10-18 23:09 UTC, stnguyen90 commented on Dockerfile
> +  && cd php-ext-lz4 \
And this is how you check out a specific commit:
```suggestion
RUN git clone --recursive --depth 1 https://github.com/kjdev/php-ext-lz4.git \
  && cd php-ext-lz4 \
  && git reset --hard $PHP_LZ4_COMMIT \
```

2022-10-19 07:17 UTC, aloks98 commented
Alright, got it!

2022-10-19 22:43 UTC, stnguyen90 approved these changes

2022-10-19 22:43 UTC, stnguyen90 commented
Thank you! 🙏

2022-10-25 08:49 UTC, christyjacob4 commented
Please sync your branch with `main` . It has fixes for the failing CI tests

2023-01-17 12:39 UTC, christyjacob4 approved these changes

2023-01-17 12:39 UTC, christyjacob4 commented
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+org%3Aopen-runtimes+label%3Ahacktoberfest+created%3A%3E2021-01-01+state%3Aopen&type=issues&s=updated&o=asc) and help make Appwrite better :)

2023-01-18 08:17 UTC, merged