Feat 3995 add brotli compression
utopia-php/storage pull request #57
Opened 2022-10-04 02:32 UTC by mattschlosser

For appwrite/appwrite#3995 

Brotli compression is optimal for compression of large text files. It does not work well, if at all, on images, sometimes resulting in larger sizes when used on images

2022-10-18 00:33 UTC, stnguyen90 requested changes
Successful local tests:

<img width="1062" alt="image" src="https://user-images.githubusercontent.com/1477010/196308255-cbc9554f-1ab7-4bc3-a538-0ba6694b16ce.png">

2022-10-18 00:33 UTC, stnguyen90 commented on Dockerfile
> +ENV PHP_BROTLI_VERSION="master"
Let's pin the version instead of using `mater`:

```suggestion
ENV PHP_BROTLI_VERSION="4504e4186e79b197cfcb75d4d09aa47ef7d92fe"
```

2022-10-18 00:33 UTC, stnguyen90 commented on tests/Storage/Compression/Algorithms/BrotliTest.php
> +namespace Utopia\Tests;
Would you please use:

```suggestion
namespace Tests\Storage\Compression\Algorithms;
```

to match psr-4 standards?

2022-10-18 00:34 UTC, stnguyen90 commented
@mattschlosser Great PR! 🤯 We left some comments during the review, please check them out.

2022-10-18 23:02 UTC, stnguyen90 requested changes
@mattschlosser, sorry some more changes, please. 🙏

2022-10-18 23:02 UTC, stnguyen90 commented on Dockerfile
> + && cd php-ext-brotli \
Also, it looks like you can't checkout a commit sha like this. Let's update it to:

```suggestion
RUN git clone --recursive --depth 1 https://github.com/kjdev/php-ext-brotli.git \
 && cd php-ext-brotli \
 && git reset --hard $PHP_BROTLI_COMMIT \
```

2022-10-18 23:15 UTC, mattschlosser commented on Dockerfile
> -RUN git clone --recursive --depth 1 --branch $PHP_ZSTD_VERSION https://github.com/kjdev/php-ext-zstd.git \
See full commit message on [ecca6ee](https://github.com/utopia-php/storage/pull/57/commits/ecca6eea80b3ae2e46c26be2dc942f660c488817)

Perhaps it is better to do this in a separate PR?

2022-10-18 23:23 UTC, stnguyen90 commented on Dockerfile
> -RUN git clone --recursive --depth 1 --branch $PHP_ZSTD_VERSION https://github.com/kjdev/php-ext-zstd.git \
Sorry I missed the commit message. Ya, let's leave it the way it was for now.

2022-10-19 22:46 UTC, stnguyen90 approved these changes
@mattschlosser Hey 👋 awesome work on your PR! We've approved your work and it'll be merged soon!

2022-10-25 08:49 UTC, christyjacob4 commented
Please sync your branch with `main` . It has fixes for the failing CI tests

2022-12-20 11:36 UTC, christyjacob4 commented
@mattschlosser sorry but it looks like there are still some conflicts. Please resolve them

2023-01-27 13:51 UTC, merged

2023-01-27 13:51 UTC, christyjacob4 commented
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+org%3Aopen-runtimes+label%3Ahacktoberfest+created%3A%3E2021-01-01+state%3Aopen&type=issues&s=updated&o=asc) and help make Appwrite better :)