Add BZIP2 compression algorithm
utopia-php/storage pull request #58
Opened 2022-10-07 15:43 UTC by Luke-Shepp

Creates a new compression class to support BZIP2 compression and decompression, with accompanied unit test.

```
➜  utopia-php-storage git:(feat-bzip2-compression) ✗ ./vendor/bin/phpunit --filter BZIP2Test
PHPUnit 9.5.25 by Sebastian Bergmann and contributors.

....                                                                4 / 4 (100%)

Time: 00:01.870, Memory: 17.55 MB

OK (4 tests, 12 assertions)
```

2022-10-18 00:38 UTC, stnguyen90 requested changes
@Luke-Shepp Great PR! 🤯 We left some comments during the review, please check them out.

2022-10-18 00:38 UTC, stnguyen90 commented on tests/Storage/Compression/Algorithms/BZIP2Test.php
> +namespace Utopia\Tests;
Would you please use:

```suggestion
namespace Tests\Storage\Compression\Algorithms;
```

to match psr-4 standards?

2022-10-19 22:56 UTC, stnguyen90 commented
Also, it looks like the tests are failing:

<img width="711" alt="image" src="https://user-images.githubusercontent.com/1477010/196819785-c5241eb9-91ab-4c04-a80a-977c8174a0d6.png">

2022-10-25 08:49 UTC, christyjacob4 commented
Please sync your branch with `main` . It has fixes for the failing CI tests

2022-10-31 16:24 UTC, Meldiron commented
Thank you so much for the PR 🤩. We're adding the `hacktoberfest-accepted` label to ensure this PR counts towards your Hacktoberfest contributions count. With that said, please stay active on this PR to address any comments once you receive a review. Happy Hacktoberfest! 🎃

2023-01-22 20:53 UTC, closed without merging