feat: add xz compression
utopia-php/storage pull request #59
Opened 2022-10-10 18:06 UTC by unickorn

https://github.com/appwrite/appwrite/issues/4003

2022-10-18 00:50 UTC, stnguyen90 requested changes
Local tests look good:

<img width="1184" alt="image" src="https://user-images.githubusercontent.com/1477010/196309941-56370898-ebb1-4196-97dc-e01bee69d911.png">

2022-10-18 00:50 UTC, stnguyen90 commented on Dockerfile
> +RUN git clone https://github.com/codemasher/php-ext-xz.git \
Let's use release 1.1.2 instead of the default branch.

2022-10-18 00:50 UTC, stnguyen90 commented on tests/Storage/Compression/Algorithms/XZTest.php
> +namespace Utopia\Tests\Compression\Algorithms;
Would you please use:

```suggestion
namespace Tests\Storage\Compression\Algorithms;
```
to comply with psr4 autoload standards.

2022-10-18 00:51 UTC, stnguyen90 commented
@Unickorn Great PR! 🤯 We left some comments during the review, please check them out.

2022-10-18 22:36 UTC, stnguyen90 approved these changes
Tests are still passing!

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/1477010/196557957-2302c554-43b5-44c4-8681-2bdd1c1df479.png">

@Unickorn Hey 👋 awesome work on your PR! We've approved your work and it'll be merged soon!

2022-10-25 08:49 UTC, christyjacob4 commented
Please sync your branch with `main` . It has fixes for the failing CI tests

2022-12-20 22:47 UTC, christyjacob4 commented
@unickorn please resolve the merge conflicts

2023-01-27 13:38 UTC, christyjacob4 commented on Dockerfile
> +  && cd php-ext-xz \
This looks like a leftover. Can you please check

2023-04-06 22:34 UTC, merged

2023-04-06 22:34 UTC, christyjacob4 commented
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+org%3Aopen-runtimes+label%3Ahacktoberfest+created%3A%3E2021-01-01+state%3Aopen&type=issues&s=updated&o=asc) and help make Appwrite better :)