Add code quality analysis with PHPStan
utopia-php/storage pull request #62
Opened 2022-10-13 18:45 UTC by abhishekdd

Closes [🔎 Add Code Analyzer To ‘utopia-php/storage’ #4374](https://github.com/appwrite/appwrite/issues/4374)

Implements code quality analysis into the repository. This allows running **composer check** to check for errors. Also auto-checks every PR with composer check to create failed test if there are code quality issues.

This PR also fixes the code quality issues identified by PHPStan up to analysis level 5.

2022-10-25 08:48 UTC, christyjacob4 commented
Please sync your branch with `main` . It has fixes for the failing CI tests

2022-10-28 22:44 UTC, stnguyen90 requested changes
@abhishekdd would you please sync with main and fix the merge conflicts?

2022-10-31 16:39 UTC, PineappleIOnic commented
Thank you so much for the PR 🤩. We're adding the `hacktoberfest-accepted` label to ensure this PR counts towards your Hacktoberfest contributions count. With that said, please stay active on this PR to address any comments once you receive a review. Happy Hacktoberfest! 🎃

2023-04-06 14:06 UTC, christyjacob4 commented
@abhishekdd thanks a lot for your contributions during Hacktoberfest 2022!  

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord. 

2023-08-01 21:41 UTC, stnguyen90 commented
@abhishekdd would you be able to fix the merge conflicts so we can merge this in?

2026-07-21 09:49 UTC, closed without merging