Feat 3996 bzip2 compression
utopia-php/storage pull request #89
Opened 2023-10-03 16:28 UTC by AkhileshJyotishi

# Create BZIP2 Compression Class and Unit Test

## Description

This pull request introduces a new compression class to support BZIP2 compression and decompression, along with its accompanying unit test. The BZIP2 compression algorithm is now available for use in our storage library, enhancing its capabilities.

## Installation Instructions (for Linux-based distributions)

Before using the BZIP2 compression class, you need to install the required dependency. You can do this using the following command on Linux-based distributions:

```shell
sudo apt install php-bz2
```

## Testing command

```shel
./vendor/bin/phpunit  ./tests/Storage/Compression/Algorithms/BZIP2TEST.php
```
 ## Attached Screenshot
 
![Screenshot_20231003_214438](https://github.com/utopia-php/storage/assets/119918405/945e09b9-3f08-4a75-a14a-3c92d45c07b6)

closes: https://github.com/appwrite/appwrite/issues/3996

2023-10-31 12:02 UTC, loks0n requested changes

2023-10-31 12:02 UTC, loks0n commented on tests/Storage/Compression/Algorithms/BZIP2TEST.php
> +        $this->assertGreaterThan($dataSize, $demoSize);
I don't think this is necessary

2023-10-31 12:04 UTC, loks0n requested changes
Please also fix the linter by running `composer run format`

2023-10-31 17:42 UTC, AkhileshJyotishi commented
please give me hacktoberfest accepted tag i will update it soon

2023-10-31 17:42 UTC, AkhileshJyotishi commented
@loks0n

2023-10-31 18:06 UTC, loks0n commented
Please don't spam. You already have the tag.

2023-11-14 02:20 UTC, tessamero commented
Hi @AkhileshJyotishi 

Thank you for your contribution to Hacktoberfest 2023! We've noticed that your PR is still pending and requires some updates based on our engineering team's feedback.

We would love to see your PR successfully merged and send you the Appwrite swag as a token of appreciation. To remain eligible for the swag, please address the pending suggestions and/or ensure the tests pass  by **Friday, November 17th**. If the PR isn't updated by then, we will unfortunately have to close it due to the end of the Hacktoberfest event.

2024-04-08 20:12 UTC, gewenyu99 commented
Hey there! There were a lot of big PRs during this Hacktoberfest, and we wanted to give everyone ample time to collaborate with our engineering team. If you were able to merge your PRs during October, amazing. If it’s still not merged, don’t worry about it either. Either way, we’ve got your Hacktoberfest swag minted and ready to ship. 

Please comment with your Discord username here so we can contact you about your shipping information to deliver your Hacktoberfest swag.

2024-05-04 10:40 UTC, AkhileshJyotishi commented
@gewenyu99   

my username akhilesh_32621

2026-05-01 15:06 UTC, closed without merging