Added ArubaCloud Storage adapter
utopia-php/storage pull request #98
Opened 2023-10-20 02:36 UTC by bannu0snake

2023-11-01 00:20 UTC, stnguyen90 requested changes
Great PR! 🤯 We left some comments during the review, please check them out.

Please also make sure to run the formatter to fix the lint errors and provide a screenshot of successful tests.

2023-11-01 00:20 UTC, stnguyen90 commented on src/Storage/Device/ArubaCloud.php
> +        $this->headers['host'] = 's3.arubacloud.com/' . $bucket;
I don't think you can put a path in the host header 🧐

2023-11-01 00:20 UTC, stnguyen90 commented on src/Storage/Device/ArubaCloud.php
> +     *
Would you please add a link to the reference material you used to determine the regions?

2023-11-14 02:28 UTC, tessamero commented
Hello @bannu0snake ,

Thank you for your contribution to Hacktoberfest 2023! We've noticed that your PR is still pending and requires some updates based on our engineering team's feedback.

We would love to see your PR successfully merged and send you the Appwrite swag as a token of appreciation. To remain eligible for the swag, please address the pending suggestions and/or ensure the tests pass  by **Friday, November 17th**. If the PR isn't updated by then, we will unfortunately have to close it due to the end of the Hacktoberfest event.

Looking forward to your updates and thank you!

2024-04-08 20:05 UTC, gewenyu99 commented
Hey there! There were a lot of big PRs during this Hacktoberfest, and we wanted to give everyone ample time to collaborate with our engineering team. If you were able to merge your PRs during October, amazing. If it’s still not merged, don’t worry about it either. Either way, we’ve got your Hacktoberfest swag minted and ready to ship. 

Please comment with your Discord username here so we can contact you about your shipping information to deliver your Hacktoberfest swag.

2024-04-09 05:46 UTC, bannu0snake commented
thanks @gewenyu99 my discord username is `bannu0snake`  . please let me know if you are not able to reach out to me via discord.

2024-04-19 15:43 UTC, gewenyu99 commented
I'm collecting the usernames in a big spread sheet rn. It's a lot of people to contact, so I'll let you know!

2026-07-21 09:49 UTC, closed without merging