[STORAGE]:Implementation of Exoscale adapter , Issue #6412 in appwrite repository
utopia-php/storage pull request #99
Opened 2023-10-20 07:15 UTC by Atharva1723

I have completed the partial implementation of the Exoscale adapter . Please review the PR and let me know what changes need to be made.

2023-10-21 13:45 UTC, Atharva1723 commented
@stnguyen90 Can you review this PR?

2023-10-30 17:53 UTC, Atharva1723 commented
Can this PR be reviewed? So that the necessary changes can be done by me

2023-11-01 00:23 UTC, stnguyen90 requested changes
Great PR! 🤯 We left some comments during the review, please check them out.

Please make sure to run the formatter to fix the lint errors and attach screenshots of successful tests.

2023-11-01 00:23 UTC, stnguyen90 commented on src/Storage/Device/Exoscale.php
> +     */
Would you please provide a link to reference material for this info?

2023-11-01 00:23 UTC, stnguyen90 commented on src/Storage/Device/Exoscale.php
> +            $this->headers['host'] = $this->regionEndpointMap[$region];
The host header shouldn't include the URL scheme.

2023-11-01 04:28 UTC, stnguyen90 requested changes
Please see my comments.

In addition, please fix the lint errors and attach a screenshot of successful tests to the PR.

2023-11-01 04:28 UTC, stnguyen90 commented on src/Storage/Device/Exoscale.php
> +     */
```suggestion
    /**
     * Exoscale Regions constants
     * https://community.exoscale.com/documentation/platform/exoscale-datacenter-zones/
     */
```

2023-11-01 04:28 UTC, stnguyen90 commented on src/Storage/Device/Exoscale.php
> +            $this->headers['host'] = $this->regionEndpointMap[$region];
What happened to regionEndpointMap?

2023-11-01 10:29 UTC, Atharva1723 commented
@stnguyen90 I have referred the configuration from https://community.exoscale.com/documentation/storage/quick-start/

2023-11-02 22:01 UTC, stnguyen90 requested changes
Please make sure to run the formatter to fix the lint errors and attach screenshots of successful tests.

2023-11-03 09:45 UTC, loks0n requested changes

2023-11-03 09:45 UTC, loks0n commented on .github/workflows/tests.yml
> +        devices: [BackblazeTest, DOSpacesTest, ExoscaleTest,LinodeTest, LocalTest, S3Test, WasabiTest]
Can you add a space here
```suggestion
        devices: [BackblazeTest, DOSpacesTest, ExoscaleTest, LinodeTest, LocalTest, S3Test, WasabiTest]
```

2023-11-03 10:08 UTC, Atharva1723 commented
Why are the linter and tests failing

2023-11-03 10:18 UTC, Atharva1723 commented
> Please make sure to run the formatter to fix the lint errors and attach screenshots of successful tests.

Where is the formatter ?

2023-11-06 10:18 UTC, loks0n commented
> Where is the formatter ?

You can see the errors under the 'Checks' tab.

To run the formatter do `compose run format`

Please try to consult the CONTRIBUTING.md if you are stuck

2023-11-13 22:25 UTC, tessamero commented
Hello @Atharva1723 

Thank you for your contribution to Hacktoberfest 2023! We've noticed that your PR is still pending and requires some updates based on our engineering team's feedback.

We would love to see your PR successfully merged and send you the Appwrite swag as a token of appreciation. To remain eligible for the swag, please address the pending suggestions by **Friday, November 17th**. If the PR isn't updated by then, we will unfortunately have to close it due to the end of the Hacktoberfest event.

Looking forward to your updates and thank you!

2023-11-14 02:11 UTC, Atharva1723 commented
> Hello @Atharva1723
> 
> Thank you for your contribution to Hacktoberfest 2023! We've noticed that your PR is still pending and requires some updates based on our engineering team's feedback.
> 
> We would love to see your PR successfully merged and send you the Appwrite swag as a token of appreciation. To remain eligible for the swag, please address the pending suggestions by **Friday, November 17th**. If the PR isn't updated by then, we will unfortunately have to close it due to the end of the Hacktoberfest event.
> 
> Looking forward to your updates and thank you!

I am working on the PR rn will commit the changes as soon as possible..

2023-11-15 08:51 UTC, Atharva1723 commented
I have run the formatter.

2024-04-08 20:06 UTC, gewenyu99 commented
Hey there! There were a lot of big PRs during this Hacktoberfest, and we wanted to give everyone ample time to collaborate with our engineering team. If you were able to merge your PRs during October, amazing. If it’s still not merged, don’t worry about it either. Either way, we’ve got your Hacktoberfest swag minted and ready to ship. 

Please comment with your Discord username here so we can contact you about your shipping information to deliver your Hacktoberfest swag.

2024-04-09 06:24 UTC, Atharva1723 commented
> Hey there! There were a lot of big PRs during this Hacktoberfest, and we wanted to give everyone ample time to collaborate with our engineering team. If you were able to merge your PRs during October, amazing. If it’s still not merged, don’t worry about it either. Either way, we’ve got your Hacktoberfest swag minted and ready to ship.
> 
> Please comment with your Discord username here so we can contact you about your shipping information to deliver your Hacktoberfest swag.

My Discord username: phoenixop17

2024-04-19 15:43 UTC, gewenyu99 commented
Adding your name to a big spreadsheet to reach out. Thanks for your patience!

2024-04-20 03:53 UTC, Atharva1723 commented
sadd

2024-04-20 03:55 UTC, Atharva1723 commented
adas

2026-07-21 09:49 UTC, closed without merging